apiVersion: v1
kind: Pod
metadata:
  name: peer1-0
  labels:
    app: peer1-0
spec:
  containers:
  - name: shardkv-container
    image: local/shardkv-peer
    imagePullPolicy: Never
    command: ['shardkv']
    ports:
    - name: peer1-0-client
      containerPort: 3000
    - name: peer1-0-raft
      containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: peer1-0
spec:
  type: NodePort
  selector:
    app: peer1-0
  ports:
  - port: 3000
    targetPort: peer1-0-client
    name: client-port
  - port: 3001
    targetPort: peer1-0-raft
    name: raft-port

---
apiVersion: v1
kind: Pod
metadata:
  name: peer0-0
  labels:
    app: peer0-0
spec:
  containers:
  - name: shardmaster-container
    image: local/shardmaster-peer
    imagePullPolicy: Never
    command: ['shardmaster']
    ports:
    - name: peer0-0-client
      containerPort: 3000
    - name: peer0-0-raft
      containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: peer0-0
spec:
  type: NodePort
  selector:
    app: peer0-0
  ports:
  - port: 3000
    targetPort: peer0-0-client
    name: client-port
  - port: 3001
    targetPort: peer0-0-raft
    name: raft-port   